<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY2oRaPd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY2oRaPd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY2oRaPd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY2oRaPd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY2oRaPd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y2oRaPd',
    'container.build_id' => 'a2424191',
    'container.build_time' => 1681384932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY2oRaPd');
