<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNk4Ku9D\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNk4Ku9D/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNk4Ku9D.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNk4Ku9D\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNk4Ku9D\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nk4Ku9D',
    'container.build_id' => '379cea8f',
    'container.build_time' => 1682876259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNk4Ku9D');
