<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEPxtibO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEPxtibO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEPxtibO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEPxtibO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEPxtibO\App_KernelDevDebugContainer([
    'container.build_hash' => 'EPxtibO',
    'container.build_id' => '6b677929',
    'container.build_time' => 1680909935,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEPxtibO');
